-- Vulpes Color Palette
-- A cyberpunk neon theme with monthly color variants
-- https://github.com/ejfox/vulpes.nvim

local M = {}

-- The core vulpes palette (reddishnovember - the OG)
M.dark = {
  -- Backgrounds
  bg = "#000000",
  bg_alt = "#0d0d0d",
  bg_float = "#0d0d0d",
  bg_popup = "#121212",
  bg_visual = "#6b1a3d",
  bg_search = "#5c0030",
  bg_cursorline = "#2a1520",

  -- Foregrounds
  fg = "#f2cfdf",
  fg_dim = "#c490a8",
  fg_dark = "#735865",

  -- Core accent (the signature vulpes pink)
  base = "#e60067",
  base_bright = "#ff277d",

  -- Semantic colors
  error = "#a0f7fc", -- Bright teal (inverted for pop)
  warning = "#ffaa00",
  success = "#ffffff",
  info = "#ff0095",
  hint = "#ff4d9d",

  -- Syntax colors — generated by palette-derive.py (do not hand-edit hex values)
  -- Cluster anchors: PINK H=341° · AMBER H=65° · VFD H=176° · TEAL H=202.3° (fixed)
  -- Brightness within each cluster is encoded in OKLCH L and C parameters.
  comment     = "#6eedf7",  -- OKLCH(0.878, 0.113, 202.3°) P31 phosphor — pinned
  keyword     = "#ff1bca",  -- OKLCH(0.679, 0.284, 341.1°) pink full
  func        = "#ffffff",  -- pure white — max contrast
  string      = "#f5f5f5",  -- near-white — content
  number      = "#f99600",  -- OKLCH(0.759, 0.170,  64.9°) amber full
  boolean     = "#db8925",  -- OKLCH(0.701, 0.145,  65.2°) amber mid
  constant    = "#db8925",  -- OKLCH(0.701, 0.145,  65.2°) amber mid
  macro       = "#f99600",  -- OKLCH(0.759, 0.170,  64.9°) amber full
  type        = "#00d5b4",  -- OKLCH(0.780, 0.146, 176.1°) VFD full
  builtin     = "#00d5b4",  -- OKLCH(0.780, 0.146, 176.1°) VFD full
  namespace   = "#44a28d",  -- OKLCH(0.650, 0.095, 176.1°) VFD dim
  variable    = "#ae498f",  -- OKLCH(0.560, 0.155, 341.1°) pink mid
  parameter   = "#d048a9",  -- OKLCH(0.620, 0.199, 341.0°) pink hi-mid
  property    = "#8c4876",  -- OKLCH(0.501, 0.109, 340.8°) pink lo-mid
  operator    = "#6b445d",  -- OKLCH(0.440, 0.065, 341.3°) pink ghost
  punctuation = "#735865",  -- near-neutral — mounting hardware (pinned)
  tag         = "#ff1bca",  -- == keyword
  heading     = "#ff1bca",  -- == keyword

  -- UI elements
  selection = "#6b1a3d",
  selection_fg = "#ffffff",
  cursor = "#e60067",
  linenr = "#735865",
  border = "#e60067",

  -- Git/Diff (HCL-harmonized with vulpes base hue ~340°)
  git_add = "#b4d455",      -- Warm chartreuse (Hue ~85°)
  git_change = "#ffaa00",
  git_delete = "#c44569",   -- Dusty rose-burgundy (Hue ~350°)
  diff_text = "#e8b4c8",    -- Soft pink for changed text

  -- Terminal colors (ANSI)
  black = "#0d0d0d",
  red = "#ff001e",
  green = "#ffffff",
  yellow = "#ffaa00",
  blue = "#ff0095",
  magenta = "#ff24ab",
  cyan = "#6eedf7",
  white = "#f2cfdf",
  bright_black = "#735865",
  bright_red = "#ff2e2e",
  bright_green = "#ffffff",
  bright_yellow = "#ffcc00",
  bright_blue = "#ff2daf",
  bright_magenta = "#ff40c7",
  bright_cyan = "#a0f7fc",
  bright_white = "#ffffff",
}

-- Light variant
M.light = {
  -- Backgrounds
  bg = "#fefefe",
  bg_alt = "#f5f0f2",
  bg_float = "#f5f0f2",
  bg_popup = "#ebe5e8",
  bg_visual = "#ffd6e8",
  bg_search = "#ffe0ed",
  bg_cursorline = "#fff0f5",

  -- Foregrounds
  fg = "#1a0a10",
  fg_dim = "#4a3040",
  fg_dark = "#6b5060",

  -- Core accent
  base = "#c50058",
  base_bright = "#e60067",

  -- Semantic colors
  error = "#008b8f",
  warning = "#b87700",
  success = "#006600",
  info = "#c50058",
  hint = "#d84d8a",

  -- Syntax colors — generated by palette-derive.py (do not hand-edit hex values)
  -- Same cluster anchors as dark, L inverted for white bg (lower L = more contrast on white)
  comment     = "#008b8f",  -- OKLCH(0.578, 0.098, 198.4°) dark phosphor teal — pinned
  keyword     = "#900071",  -- OKLCH(0.440, 0.191, 340.8°) pink full (dark on white)
  func        = "#1a0a10",  -- near-black — max contrast on white
  string      = "#1a0a10",  -- near-black — content
  number      = "#864e00",  -- OKLCH(0.479, 0.108,  64.7°) amber full (dark)
  boolean     = "#965800",  -- OKLCH(0.520, 0.117,  64.7°) amber mid (dark)
  constant    = "#965800",  -- OKLCH(0.520, 0.117,  64.7°) amber mid (dark)
  macro       = "#864e00",  -- OKLCH(0.479, 0.108,  64.7°) amber full (dark)
  type        = "#006756",  -- OKLCH(0.459, 0.086, 176.1°) VFD full (dark)
  builtin     = "#006756",  -- OKLCH(0.459, 0.086, 176.1°) VFD full (dark)
  namespace   = "#237967",  -- OKLCH(0.521, 0.085, 175.8°) VFD dim (dark)
  variable    = "#9f4c85",  -- OKLCH(0.539, 0.131, 340.8°) pink mid (dark)
  parameter   = "#9e2f7f",  -- OKLCH(0.499, 0.170, 341.0°) pink hi-mid (dark)
  property    = "#a0638b",  -- OKLCH(0.579, 0.095, 340.9°) pink lo-mid (dark)
  operator    = "#9e7990",  -- OKLCH(0.619, 0.056, 341.1°) pink ghost (dark)
  punctuation = "#a08090",  -- near linenr — pinned
  tag         = "#900071",  -- == keyword
  heading     = "#900071",  -- == keyword

  -- UI elements
  selection = "#ffd6e8",
  selection_fg = "#1a0a10",
  cursor = "#c50058",
  linenr = "#a08090",
  border = "#c50058",

  -- Git/Diff (HCL-harmonized with vulpes base hue ~340°, for light bg)
  git_add = "#5a7a20",      -- Dark chartreuse (Hue ~85°)
  git_change = "#b87700",
  git_delete = "#9e3050",   -- Dark dusty rose (Hue ~350°)
  diff_text = "#8a4060",    -- Muted rose for changed text

  -- Terminal colors (ANSI)
  black = "#1a0a10",
  red = "#cc0000",
  green = "#006600",
  yellow = "#b87700",
  blue = "#c50058",
  magenta = "#a80070",
  cyan = "#008b8f",
  white = "#f5f0f2",
  bright_black = "#6b5060",
  bright_red = "#e50000",
  bright_green = "#008800",
  bright_yellow = "#d99000",
  bright_blue = "#e60067",
  bright_magenta = "#c5008a",
  bright_cyan = "#00a0a5",
  bright_white = "#fefefe",
}

-- Get palette based on background
function M.get(variant)
  variant = variant or (vim.o.background == "light" and "light" or "dark")
  return M[variant] or M.dark
end

return M
